baseURL = "https://carlinhoshk.github.io/cblog/"
languageCode = "pt-br"
title = "cblog"
theme = "hugo-theme-terminal"
pagination.pagerSize = 5

[markup.goldmark.renderer]
unsafe = true

[params]
contentTypeName = "posts"
showMenuItems = 2
fullWidthTheme = false
centerTheme = false

[languages]
[languages.pt]
languageName = "Português"
title = "cblog"
subtitle = "código, sistemas e backend"
keywords = "linux, low-level, programação, sistemas, arch, kernel"
copyright = "© Carlos Oliveira"

menuMore = "Mais"
readMore = "Ler mais"
readOtherPosts = "Outros posts"

[languages.pt.params.logo]
logoText = "cblog"
logoHomeLink = "/cblog/"

[languages.pt.menu]
[[languages.pt.menu.main]]
identifier = "about"
name = "sobre"
url = "/about"

[[languages.pt.menu.main]]
identifier = "posts"
name = "posts"
url = "/posts"
